package comp1110.ass2;

import java.util.Set;

public class Arboretum {
    /* DO NOT EDIT THIS FILE YET!
     * After D2B, upstream will have a large update to this file to include the
     * declarations of static methods you will need to implement to interface
     * your working game code with our tests. We are holding them back so as to
     * not negatively influence your early design work.
     */
}
